# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: 🐞 Bug report
description: Create a report to help us improve SeqAn3.
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Does this problem persist on the current main?
    description: Update to the latest main branch of SeqAn and see if the issue persists.
    options:
    - label: I have verified the issue on the current main
      required: true
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this code...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Operating system**: Ubuntu 20.04
        - **SeqAn version**: 3.1.0 or 8a4f31cb7 (provide tag or commit as applicable)
        - **Compiler**: gcc 11.2
    value: |
        - Operating system:
        - SeqAn version:
        - Compiler:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      If you already know how to fix the issue, you can directly create a pull-request instead of an issue.
      See the [contributor guide](https://docs.seqan.de/seqan3/main_user/about_contributing.html) for more details.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
