#!/usr/bin/bash

# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: BSD-3-Clause

set -Eeuo pipefail

SDSL_REPO_PATH="${PWD}/sdsl-lite/"
CXX=${CXX:-c++}
CPP_AMALGAMATE=cpp-amalgamate

if [[ ! -d "${SDSL_REPO_PATH}" || ! -f "${SDSL_REPO_PATH}"/include/sdsl/version.hpp ]]; then
    mkdir -p "${SDSL_REPO_PATH}"
    wget -q -O- https://github.com/xxsds/sdsl-lite/archive/refs/heads/master.tar.gz | tar -xz -C "${SDSL_REPO_PATH}" --strip-components=1
fi

if ! command -v "${CPP_AMALGAMATE}" &> /dev/null; then
    if [[ ! -f cpp-amalgamate ]]; then
        wget -q https://github.com/Felerius/cpp-amalgamate/releases/download/1.0.1/cpp-amalgamate-x86_64-unknown-linux-gnu -O cpp-amalgamate
    fi

    chmod +x cpp-amalgamate
    CPP_AMALGAMATE=${PWD}/cpp-amalgamate
fi

cat <<EOL > includes.cpp
#include <sdsl/bit_vectors.hpp>
#include <sdsl/int_vector.hpp>
#include <sdsl/suffix_arrays.hpp>
#include <sdsl/suffix_trees.hpp>
EOL

"${CPP_AMALGAMATE}" --quiet --dir "${SDSL_REPO_PATH}/include" --cyclic-include warn --output amalgamated.hpp includes.cpp
grep -v "#include <sdsl/" amalgamated.hpp > decycled.hpp
# This command strips all comments.
CONTENT=$(${CXX} -fpreprocessed -dD -E -P -w decycled.hpp)

cat <<EOL > sdsl-lite.hpp
// SPDX-FileCopyrightText: 2016 SDSL Project Authors
// SPDX-License-Identifier: BSD-3-Clause

// This file was generated by https://github.com/seqan/seqan3/blob/main/test/scripts/amalgamate-sdsl.sh

#pragma once

// clang-format off
${CONTENT}
// clang-format on

EOL

echo "${PWD}/sdsl-lite.hpp"
